name: Deploy PharmacyBot

on:
  push:
    branches: [ master ]
  workflow_dispatch:  # Дозволяє запускати workflow вручну

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        python -m unittest tests.test_db tests.test_pharmacy

    - name: Deploy bot
      if: success()  # Запускати деплой тільки якщо тести пройшли успішно
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        BD_TOKEN: ${{ secrets.BD_TOKEN }}
      run: |
        python PharmacyBot.py